package api.templates;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import api.templates.PrimaryKey;

import org.springframework.data.annotation.Id;

import javafx.util.Pair;

import java.util.*;


@DynamoDBDocument(tableName = "Template")
public class Templates {
    @Id
    private PrimaryKey key;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "SlideCount")
    private Int SlideCount;

    @DynamoDBAttribute(attributeName = "Slides")
    private List<String> slides; 

    @DynamoDBAttribute(attributeName = "partitions")
    private List<Int> partitions; 

    @DynamoDBAttribute(attributeName = "Text")
    private List<String> Text;

    @DynamoDBAttribute(attributeName = "SlideDuration")
    private List<Int> SlideDuration;

    @DynamoDBAttribute(attributeName = "Shapes")
    private List<String> Shapes;

    @DynamoDBAttribute(attributeName = "Images") 
    private List<String> Images;

    @DynamoDHashKey(attributeName = "UserId")
    @DynamoDBAutoGeneratedKey
    public String getUserId() {
        return key.getUserId();
    }

    public void setUserId() {
        if (key == null) {
            key = new PrimaryKey();
        }
        UUID newUUID = UUID.randomUUID();
        key.setUserId(newUUID.toString());
    }

    @DynamoDBRangeKey(attributeName = "TemplateId")
    @DynamoDBAutoGeneratedKey
    public String getTemplateId() {
        return key.getTemplateId();
    }

    public void setTemplateId() {
        if (key == null) {
            key = new PrimaryKey();
        }
        UUID newUUID = UUID.randomUUID();
        key.setTemplateId(newUUID.toString());
    }

}

