package api.templates;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import api.templates.PrimaryKey;

import org.springframework.data.annotation.Id;

import javafx.util.Pair;

import java.util.*;


@DynamoDBTable(tableName = "Template")
public class Templates {
    @Id
    private PrimaryKey key;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "Slides")
    private List<String> slides; 

    @DynamoDBAttribute(attributeName = "partitions")
    private List<Int> partitions; 

    @DynamoDBAttribute(attributeName = "Text")
    private List<String> Text;

    @DynamoDBAttribute(attributeName = "SlideDuration")
    private List<Int> SlideDuration;

    @DynamoDBAttribute(attributeName = "Shapes")
    private List<String> Shapes;

    @DynamoDBAttribute(attributeName = "Images") 
    private List<String> Images;

    @DynamoDHashKey(attributeName = "UserId")
    @DynamoDBAutoGeneratedKey
    public String getUserId() {
        return key.getUserId();
    }

    public void setUserId() {
        if (key == null) {
            key = new PrimaryKey();
        }
        UUID newUUID = UUID.randomUUID();
        key.setUserId(newUUID.toString());
    }

    @DynamoDBRangeKey(attributeName = "TemplateId")
    @DynamoDBAutoGeneratedKey
    public String getTemplateId() {
        return key.getTemplateId();
    }

    public void setTemplateId() {
        if (key == null) {
            key = new PrimaryKey();
        }
        UUID newUUID = UUID.randomUUID();
        key.setTemplateId(newUUID.toString());
    }

    public String getName() {
        return name;
    }

    public void setName(String templateName) {
        name = TemplateName;
    }

    public List<String> getSlides() {
        return slides;
    }

    public void createSlides() {
        slides = new ArrayList<String>();
    }

    public void addSlide(String slideId) {
        slides.add(slideId);
    }

    public List<Int> getPartitions() {
        return partitions;
    }

    public void createPartitions() {
        partitions = new ArrayList<Int>();
    }

    public void addPartition(Int slideNumber) {
        partitions.add(slideNumber);
    }

    public List<String> getText() {
        return Text;
    }

    public void createText() {
        text = new ArrayList<String>();
    }

    public void addText(String data) {
        text.add(data);
    }

    public List<Int> getSlideDuration() {
        return SlideDuration;
    }

    public void createSlideDuration() {
        SlideDuration = new ArrayList<Int>();
    }

    public void addSlideDuration(Int time) {
        SlideDuration.add(time);
    }

    public List<String> getShapes() {
        return Shapes;
    }

    public void createShapes() {
        Shapes = new ArrayList<String>();
    }

    public void addShape(String shapeId) {
        ShapeId.add(shapeId);
    }

    public List<String> getImages() {
        return Images;
    }

    public void createImages() {
        Images = new ArrayList<String>();
    }

    public void addSlideDuration(String imageUrl) {
        Images.add(imageUrl);
    }
}