package api.videoAccounts;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.data.annotation.Id;

import api.videoAccounts.PrimaryKey;

import java.util.*;

@DynamoDBTable(tableName = "VideoAccounts")
public class VideoAccounts {
    @Id
    private PrimaryKey key;

    @DynamoDBAttribute(attributeName = "username")
    private String username;

    @DynamoDBAttribute(attributeName = "videosMade")
    private List<String> videosMade;

    @DynamoDBAttribute(attributeName = "videoBucketName") 
    private String videoBucketName;

    @DynamoDHashKey(attributeName = "UserId")
    @DynamoDBAutoGeneratedKey
    public String getUserId() {
        return key.getUserId();
    }

    public void setUserId() {
        if (key == null) {
            key = new PrimaryKey();
        }
        UUID newUUID = UUID.randomUUID();
        key.setUserId(newUUID.toString());
    }

    @DynamoDBRangeKey(attributeName = "VideoAccountId")
    @DynamoDBAutoGeneratedKey
    public String getVideoAccountId() {
        return key.getVideoAccountId();
    }

    public void setVideoAccountId() {
        if (key == null) {
            key = new PrimaryKey();
        }
        UUID newUUID = UUID.randomUUID();
        key.setVideoAccountId(newUUID);
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String currUsername) {
        username = currUsername;
    }

    public List<String> getMadeVideos() {
        return videosMade;
    }

    public void createMadeVideos() {
        videosMade = new ArrayList<String>();
    }

    public void addCreatedVideo(String newVideo) {
        videosMade.add(newVideo);
    }

    public void deleteVideo(String video) {
        videosMade.remove(videosMade.IndexOf(video));
    }

    public String getVideoBucket() {
        return videoBucketName;
    }

    public void setVideoBucket(String newVideoBucketName) {
        videoBucketName = newVideoBucketName;
    }

}
